from app.api import api
from flask import jsonify, request
from models import db, EventType
from Exceptions import NotFound, MethodNotAllowed, \
    Forbiden, InternalServerError, ExistingResource,\
    BadRequest, AuthError
from .authhelpers import requires_auth


@api.errorhandler(NotFound)
@api.errorhandler(Forbiden)
@api.errorhandler(MethodNotAllowed)
@api.errorhandler(InternalServerError)
@api.errorhandler(AuthError)
@api.errorhandler(ExistingResource)
def api_error(error):
    payload = dict(error.payload or ())
    payload['code'] = error.status_code
    payload['message'] = error.message
    payload['success'] = error.success
    return jsonify(payload), error.status_code


"""
This endpoint creates a new event_type
:return: returns an event_type json object
"""
@api.route("/events/types", methods=["POST"])
@requires_auth("create:event_types")
def new_event_type(token):
    name = request.json.get("name")
    description = request.json.get("description")

    if not name or not description:
        raise BadRequest("Invalid body provided")

    try:
        new_event_type = EventType(name=name, description=description)
        EventType.insert(new_event_type)
        return jsonify(new_event_type.serialize)
    except Exception as e:
        print(e)
        db.session.rollback()
        raise InternalServerError("Could not create event type")


"""
This Retrieve all events types
:return: returns a list of event type json objects
"""
@api.route("/events/types")
@requires_auth("read:event_types")
def retrieve_all_events_types(token):
    try:
        event_types = EventType.query.all()
    except Exception as e:
        print(e)
        raise InternalServerError(
            "Internal Server Error! Could not retrieve users.")

    return jsonify(
        {
            "success": True,
            "data": [event_type.serialize for event_type in event_types]
        }
    )


"""
This endpoint get an event_type with given id
:params event_id: The event Id generated by database
:return: returns an event_type json object corresponding to
         the event_type id
"""
@api.route("/events/types/<type_id>")
@requires_auth("read:event_types")
def get_event_type(token, type_id):
    try:
        event_type = EventType.query.filter_by(id=type_id).first()
    except Exception as e:
        print(e)
        raise InternalServerError(
            "Internal Server Error! Could not retrieve events types.")
    if not event_type:
        raise NotFound(f"Event with Id {type_id} not found")
    else:
        return jsonify(
            {
                "success": True,
                "data": event_type.serialize
            }
        )


"""
This endpoint Updates an event_type with given id
:params event_id: The event Id generated by databas
:return: returns an event json object
"""
@api.route("/events/types/<type_id>", methods=["PATCH"])
@requires_auth("update:event_types")
def update_event_type(token, type_id):
    body = request.get_json()
    name = body["name"]
    description = body["description"]

    if not name or not description:
        raise BadRequest("Invalid body provided")

    try:
        event_type = EventType.query.filter_by(id=type_id).first()
    except Exception as e:
        print(e)
        raise InternalServerError(
            "Internal Server Error! Could not retrieve events.")
    if not event_type:
        raise NotFound(f"Event with Id = {type_id} not found")
    else:
        event_type.name = name
        event_type.description = description

        EventType.update(event_type)
        return jsonify(
            {
                "success": True,
                "data": event_type.serialize
            })


"""
This endpoint delete an event_type with given id
:params event_id: The event Id generated by databas
:return: returns deleted event_type Id and success of True
"""
@api.route("/events/types/<type_id>", methods=["DELETE"])
@requires_auth("delete:event_types")
def delete_event_type(token, type_id):
    try:
        event_type = EventType.query.filter_by(id=type_id).first()
    except Exception as e:
        print(e)
        raise InternalServerError(
            "Internal Server Error! Could not retrieve events types.")
    if not event_type:
        raise NotFound(f"Event with Id {type_id} not found")
    else:
        EventType.delete(event_type)
        return jsonify(
            {
                "success": True,
                "deleted": type_id,
            }), 200
