"""empty message

Revision ID: fdaef017b324
Revises: 8d5dfdd6b6a8
Create Date: 2020-04-09 07:56:04.594970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaef017b324'
down_revision = '8d5dfdd6b6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered_tickets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered_tickets', 'created_at')
    # ### end Alembic commands ###
